service: whatchangedfor

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  memorySize: 256
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  include:
    - 'views/**/*.hbs'
    - 'resources/*.json'
    - '.yarn'
    - '.pnp.cjs'
    - '.pnp.loader.mjs'

functions:
  whatchangedfor-app:
    handler: src/app/main.serverlessApp
    url: true
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  whatchangedfor-parser:
    handler: src/parser/parser.parse
    timeout: 120
    events:
      - schedule: rate(1 hour)

custom:
  serverless-offline:
    noPrependStageInUrl: true

resources:
  Resources:
    WhatChangedForDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          - 
            AttributeName: version
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          - 
            AttributeName: version
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
